
LIST P=16F877A
    include "P16F877A.inc"
    
    ; CONFIG
; __config 0xFF7A
 __CONFIG _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _BOREN_ON & _LVP_OFF & _CPD_OFF & _WRT_OFF & _CP_OFF
    ORG 0X00
    ;*****AYARLAMLAR*********
    BSF STATUS,5
    CLRF TRISB
   
    MOVLW 0XBF
    MOVWF TRISC
    MOVLW D'51';SPBRG B?T?NE 51 VEREREK HIZ AYARLAMASI
    MOVWF SPBRG
     MOVLW 0X24
    MOVWF TXSTA
    BCF STATUS,5
    MOVLW 0X90
    MOVWF RCSTA
    CLRF PORTB
    ;**********MOTOR KONTROL KISMI*****************
    BASLA
    TEST_ILERI
    CALL  RS232_RX
    SUBLW 'C'
    BTFSC STATUS,Z;
    GOTO ILERI
    TEST_GERI
    CALL  RS232_RX
    SUBLW 'G'
    BTFSC STATUS,Z;
    GOTO GERI
    TEST_SAG
    CALL  RS232_RX
    SUBLW 'F'
    BTFSC STATUS,Z;
    GOTO SAG
    TEST_SOL
    CALL  RS232_RX
    SUBLW 'E'
    BTFSC STATUS,Z;
    GOTO SOL
    TEST_DUR  
    CALL  RS232_RX
    SUBLW 'D'
    BTFSC STATUS,Z;
    GOTO DUR
    GOTO BASLA
    
    
    GERI
    MOVLW B'00001010'
    MOVWF PORTB
    GOTO BASLA
    
    ILERI
    MOVLW B'00000101'
    MOVWF PORTB
    GOTO BASLA
    
    SAG
    MOVLW B'00000001'
    MOVWF PORTB
    GOTO BASLA
    
    SOL
    MOVLW B'00000100'
    MOVWF PORTB
    GOTO BASLA

    DUR
    MOVLW B'00000000'
    MOVWF PORTB
    GOTO BASLA
    



    
    
    ;****************DATA AL***************************
    RS232_RX
    BTFSS PIR1,RCIF;BURADA PIR1 ?NTERRUP REG?STERDIR VE RCIF ?SE BUFFER?N DOLUP DOLMADIGINI ANLADIGIMIZ BAYRAKTIR.
    ;YAN? BU KODLA ?NTERRUPT REG?STER?N?N DOLUP DOLMADIGII ANLAMIS BULUNUYORUZ .EGER BAYRAK 1 ?SE BUFFER DOLMUS 0 ?SE BUFFER DOLMAMIS DMEKT?R.EGER DOLMAMISSA YAN? 0 ?SE DOLANA KADAR BEKLEMES? GEREK 
    ;OLEYSE DOLANA KADAR SUREKL? KONTROL HAL?NDE OLMALI
    GOTO $-1;B? ONCEK? SATIRDAK? KODA G?T
    MOVF RCREG,W;GELEN B?LG?Y? GELENE YUKLE
    ;BURADA W ATMAMZIZIN SEBEB? ANA DA SUB ?LE GELEN B?LG?N?N A OLUP OLMADIGINI KONTROL ED?YORDUK.BUNUN ?Ç?NDE W REG?STER?NDAK? B?LG?DEN A YI CIKARTMISTIK
    RETURN
    END

